### ISSUE TITLE
Module for language packages

### ISSUE THREAD

**Issue by lavigor** [BoardTools/upload#10]
- [x] Create instructions for language packages (format of zip files and composer.json).
- [ ] Add files composer.json to the current language packages.
- [ ] Remove all language packages other than `en` from the main release archive (update the instructions), not from the repository.
- [x] Create a table of installed language packages for each extension.
- [x] Add an ability to upload/delete language packages.

**Comment by Galixte** [comment]
I like this idea too ! Good luck for this.

**Comment by lavigor** [comment]
Language packages functionality has already been implemented.
Language packages editor is not planned for now.
Translations will be moved to Transifex soon.
