### ISSUE TITLE
New ACP features.

### ISSUE THREAD

**Issue by lavigor** [BoardTools/upload#25]
- [ ] Add a checkbox to purge the cache.
- [x] Refresh the page automatically.
- [ ] Detect possible ACP pages of extensions.

**Comment by Galixte** [comment]
For 3.1.2 ?

**Comment by lavigor** [comment]
I don't know yet.
I even don't know if the team release this extension at all, no replies for months.

**Comment by ForumHulp** [comment]
They don't want to release this is my opinion.

**Comment by Galixte** [comment]
You don’t wan to submit at the phpBB validation, why ? I see only two persons in composer.json file, you. ;)

**Comment by lavigor** [comment]
The validation topic was created in October 2014.
Since then 5 revisions were denied, each time for different reasons.
The latest revision was submitted on June 23rd, 2015 => no replies for 74 days.

I even do not know whether I need to make any fixes (my previous were also denied).

At the last time I was requested to create PRs to CDB, but my PR was closed only because it was not their.
And where's their solution now? I can't use the unpublished API (BTW shouldn't it be open source?), but my solution (ready and properly tested) was denied.

I think that the team has something in mind about our extension, but what about end users?
Why do all users need to use the outdated method of installing extensions? Isn't the whole extensions system not important for the team at all?

I thought that the installer can be a bit more important for end users than some plugins or add-ons.

**Comment by Galixte** [comment]
In French community, all users install your extension, only developpers don’t uses for other reasons which does not question the utility of your extension.

You have to presever, phpBB.com can’t ignore the benefits of your extension, we support you !

**Comment by lavigor** [comment]
Let's wait until October.
If the team does not give us a reply, maybe we can create a topic where the community can tell their opinion? Or a poll whether the extension should be validated faster.

**Comment by Galixte** [comment]
Very good idea. !-)

**Comment by ForumHulp** [comment]
Here in the Netherlands, Germany and Belgium also a lot of users.
Don't know what s happening at phpbb.com but bugs and trackers are not looked at. A simple email extensions lasts from July already without knowing anything. 
It's good to wait one month more.

**Comment by Mauron** [comment]
I'd consider to *simplify the extension to its essential goal* i.e. __letting user upload extension with no FTP access__; this means that (at the beginning, at least) you should drop additional features like upload from remote, store older versions of uploaded extensions, fancy AJAX ACP graphics and try to see if this kind of extension gets validated.

Of course, in the case you try to take this path, you should consider the minimal extension as a different one; once the minimal gets validated, you may start to merge the other functionalities.

**Comment by lavigor** [comment]
@Mauron, making backups is also the essential feature used by many users.
The extension is not denied by graphics.
FYI the version 3.1.2 was currently *never denied* with no replies from the team.
The suggested minimal version 3.1.1 was denied 5 times, I can give you the reasons if you want.

**Comment by lavigor** [comment]
Described features have already been implemented in a way so this issue can be closed.
