### ISSUE TITLE
information about my translation (Arabic)

### ISSUE THREAD

**Issue by alhitary** [BoardTools/upload#30]
original name of the language : اللغة العربية
name of the language in English : Arabic
corresponding version number of Upload Extensions : 3.1.2
the word version translated into your language : النسخة
version number of the language package (optional) : 1.0.1
comments (optional) : ...

https://github.com/BoardTools/upload/pull/29
https://github.com/BoardTools/upload/pull/28
https://github.com/BoardTools/upload/pull/27

**Comment by lavigor** [comment]
@alhitary, you do not need to create a separate PR for each edit.
You can create a new branch in your fork, do edits there and submit a PR after that.
Also you can use programs like Github for Windows to make all changes in a single commit.

**Comment by lavigor** [comment]
And I don't know the translation for the word `DOWNLOAD`.
Hmm... I think I can find those words in the core translations in the future.

**Comment by alhitary** [comment]
@lavigor
I took long time to learn the sending PR @_@
So, I still don't know how to use many things in Github
I'll make a try to learn what you mentioned, particularly Github for Windows
Thanks and sorry for inconvenience caused by me

DOWNLOAD in Arabic means تحميل

**Comment by lavigor** [comment]
Thank you!
