### ISSUE TITLE
Dutch Language

### ISSUE THREAD

**Issue by SiteHelp** [BoardTools/upload#35]
```
original name of the language, nederlands
name of the language in English, dutch
corresponding version number of Upload Extensions, 3.1.2
the word version translated into your language,versie
version number of the language package (optional), 
```

[nl.zip](https://github.com/BoardTools/upload/files/109439/nl.zip)

```
comments (optional). dutch word for download is download
```

**Comment by lavigor** [comment]
Thank you!
Added to the list of translations.
Do you want to have a GitHub branch for your translation?

BTW I plan to move to Transifex soon, please follow the updates.

**Comment by SiteHelp** [comment]
Thats fine for me, i just registered a github account, can also do that on transifex

Greetings Carlo

Van: lavigor [mailto:notifications@github.com] 
Verzonden: vrijdag 29 januari 2016 10:07
Aan: BoardTools/upload upload@noreply.github.com
CC: SiteHelp info@sitehelp.eu
Onderwerp: Re: [upload] Dutch Language (#35)

Thank you!
Added to the list of translations.
Do you want to have a GitHub branch for your translation?

BTW I plan to move to Transifex soon, please follow the updates.

**Comment by lavigor** [comment]
OK. That'll be for translations for the 3.2.0 release of the extension.
BTW Transifex supports login via GitHub.

**Comment by SiteHelp** [comment]
Just an idea would it be possible to make a page where people can download the backup files and the language files?

Greetings Carlo

Van: lavigor [mailto:notifications@github.com] 
Verzonden: vrijdag 29 januari 2016 10:15
Aan: BoardTools/upload upload@noreply.github.com
CC: SiteHelp info@sitehelp.eu
Onderwerp: Re: [upload] Dutch Language (#35)

OK. That'll be for translations for the 3.2.0 release of the extension.
BTW Transifex supports login via GitHub.

**Comment by lavigor** [comment]
[Here](https://github.com/BoardTools/upload/wiki/Translations) is the page with the links to the downloadable packages.
Or do you mean something else?

**Comment by SiteHelp** [comment]
Sorry to be unclear i mean as an extra page in your addon, I think that its not that hard if you are good in php (which I am not), people check often demo out on other pages and I think if the function was there it would be possible to easy download a package, I would at least make it available to the public so people can easy download it.

Greetings Carlo

Van: lavigor [mailto:notifications@github.com] 
Verzonden: vrijdag 29 januari 2016 10:33
Aan: BoardTools/upload upload@noreply.github.com
CC: SiteHelp info@sitehelp.eu
Onderwerp: Re: [upload] Dutch Language (#35)

Here https://github.com/BoardTools/upload/wiki/Translations  is the page with the links to the downloadable packages.
Or do you mean something else?

**Comment by lavigor** [comment]
While it can be technically possible, it requires lots of work to set the standard for the packages.
I planned to implement something like that, but now I think that I should concentrate more on other features.
