### ISSUE TITLE
Update extension with 3.2.1 changes

### ISSUE THREAD

**Issue by javiexin** [BoardTools/upload#42]
In 3.2.1, there are a number of changes introduced in the Extension Mgr context.
This extension should adapt to those changes.
One of the most significant changes is the move of a method from the Metadata Mgr to the ACP module where it is usted.
You are using this method here https://github.com/BoardTools/upload/blob/develop/includes/functions/load.php#L150, at least.
You should include the code for that function in this extension.

**Comment by lavigor** [comment]
Fixed.
