### ISSUE TITLE
readme file in develop-3.2.0 links bugs in address

### ISSUE THREAD

**Issue by raykai** [BoardTools/upload#43]
needs fixing 
some links in the file end with a dot (.) which renders the links not to work.
* For the packages uploaded from phpbb.com: [https://www.phpbb.com/customise/db/extension/upload/faq.](https://www.phpbb.com/customise/db/extension/upload/faq.)
* For the packages uploaded from [github.com: https://github.com/BoardTools/upload/wiki.](github.com: https://github.com/BoardTools/upload/wiki.)

**Comment by lavigor** [comment]
I haven't experienced this bug on GitHub or in Markdown parsing script.
But I have removed the dots so there should be no issues with them.
