### ISSUE TITLE
[3.1.2] Managment of two versions available on phpBB.com

### ISSUE THREAD

**Issue by Galixte** [BoardTools/upload#45]
Hi @lavigor,

I noted a problem under phpBB 3.1.11 with 3.1.2 version of this extension.

Some extensions on phpBB.com have two versions like “Pages” extension: https://www.phpbb.com/customise/db/extension/pages/.

If I install the 1.0.5 version of “Pages” extension, the “Upload Extensions” extension notices me that there is an update available, then if I install this it results of an update to the 2.0.2 version which is dedicated only for phpBB 3.2.x. So, I find myself in the situation where I have an extension version which is impossible to activate it and I don’t know if I can downgrade to the 1.0.5 version whithout loose some data.

So, I think it’s very problematic for beginner users, not me of course.

**Comment by lavigor** [comment]
Fixed, thank you for the report.
