### ISSUE TITLE
Fatal Error: metadata_manager::output_template_data() 

### ISSUE THREAD

**Issue by ashishpatel1992** [BoardTools/upload#46]
I just updated to phpBB 
3.2.2 from 3.2.0
I am having plugin version 3.2.0-dev
`Fatal error: Call to undefined method phpbb\extension\metadata_manager::output_template_data() in /home/centos/public_html/forum/ext/boardtools/upload/includes/compatibility/v_3_2_x.php on line 144`
Whenever I try to click on the version of a plugin it appears to have the above error.

**Comment by ashishpatel1992** [comment]
Here is the screenshot of error.
![image](https://user-images.githubusercontent.com/652311/43048458-5e122358-8e05-11e8-8bf6-a0badbd74401.png)

**Comment by lavigor** [comment]
@ashishpatel1992 this extension had a fix for this specific problem.
Please make sure that you use the latest commit from GitHub.

**Comment by ashishpatel1992** [comment]
Hi,
Thanks, I just downloaded the latest commit and it works well. I guess there was no version increment may be due to -dev branch. Issue is fixed.
But I get the Extension plugin unformatted
![image](https://user-images.githubusercontent.com/652311/43048553-10ab9c96-8e07-11e8-9baf-a4eb9cd67cf7.png)

**Comment by lavigor** [comment]
@ashishpatel1992 this is possible due to a wrong reinstallation.
Please try to disable extension, purge its data and enable it again.
If this doesn't help, try to re-upload extension files with FTP and re-install it again.

**Comment by ashishpatel1992** [comment]
Thanks a lot! renabling the extension helps!
