### ISSUE TITLE
Stuck at Loading 100% with phpBB 3.2.5

### ISSUE THREAD

**Issue by MixingOnBeat** [BoardTools/upload#47]
Updated to phpBB 3.2.5 and it seems it broke this extension.

When I upload or try to install an extension, it gets stuck at 100% Loading with the green bar animated.

Using 3.2.0-dev

**Comment by lavigor** [comment]
Hi,
thank you for your report, I've already received it on phpbb.com.

Sorry for not answering, a bit busy now.
An update will be made soon, sorry for the delay.

Best regards,
Igor

**Comment by lavigor** [comment]
@MixingOnBeat sorry once again for the delay.
Fixed in `develop-3.2.0`.

**Comment by lavigor** [comment]
For future reference: the error was caused by the update of jQuery in phpBB 3.2.5 to version 1.12.4 that was no longer compatible with `ajaxSubmit` method of jQuery Form plugin described in [this issue](https://github.com/jquery-form/form/issues/495).
