### ISSUE TITLE
language string

### ISSUE THREAD

**Issue by eunaumtenhoid** [BoardTools/upload#49]
is missing the UPDATE language string

present in html acp_upload_details in line 31 <span class = "extension_update_link" title = "{L_DOWNLOAD_LATEST}"> <i class = "fa fa-refresh fa-fw"> </ i> {L_UPDATE} </ span>

**Comment by lavigor** [comment]
The Update string comes directly from the core file.
https://github.com/phpbb/phpbb/blob/3.1.x/phpBB/language/en/common.php#L804

**Comment by eunaumtenhoid** [comment]
LOL sorry you're correct, in my case it was a conflict with another language string with the same name present in another extension, so it was not translated for me! ty
