### ISSUE TITLE
PHP Fatal Error

### ISSUE THREAD

**Issue by rmcgirr83** [BoardTools/upload#53]
When clicking on an extension in the ACP to update get this error message

> PHP Fatal error:  Uncaught Error: Call to undefined method phpbb\extension\metadata_manager::output_template_data() in /home/tinboats/public_html/forum/ext/boardtools/upload/includes/compatibility/v_3_1_x.php:283

this is on phpBB 3.3

**Comment by lavigor** [comment]
Hi,

[These lines](https://github.com/BoardTools/upload/blob/develop-3.2.0/includes/objects.php#L91-L99) need a change for the `default` to be for later and not for earlier branches of phpBB.

Fixes are not made yet, I'll have more time by February.
Sorry for the delay and for not posting this information earlier.

**Comment by rmcgirr83** [comment]
I'll take a look and do a push sometime this week

**Comment by Galixte** [comment]
This: https://github.com/BoardTools/upload/pull/54 works?

**Comment by Galixte** [comment]
OK this should fix completely the compliance with phpBB 3.3.x: https://github.com/BoardTools/upload/pull/57/files.
