### ISSUE TITLE
Extension not working correctly on phpBB 3.3.0

### ISSUE THREAD

**Issue by raykai** [BoardTools/upload#56]
HI,
will there be an update for Phpbb v3.3.0 as right now the extension not working correctly on phpBB 3.3.0

**Comment by ScottBeeson** [comment]
Same

> phpBB encountered an error building the container due to an installed extension. For this reason, all extensions have been temporarily disabled. Please try purging your forum cache. All extensions will automatically be re-enabled once the container error is resolved. If this error continues, please visit phpBB.com for support.


Exception: The file "/home/longfuse/forum.longfusegames.com/ext/boardtools/upload/config/services.yml" does not contain valid YAML: The reserved indicator "@" cannot start a plain scalar; you need to quote the scalar at line 5 (near "- @user").

#0 /home/longfuse/forum.longfusegames.com/vendor/symfony/dependency-injection/Loader/YamlFileLoader.php(117): Symfony\Component\DependencyInjection\Loader\YamlFileLoader->loadFile('/home/longfuse/...')
#1 /home/longfuse/forum.longfusegames.com/phpbb/extension/di/extension_base.php(99): Symfony\Component\DependencyInjection\Loader\YamlFileLoader->load('services.yml')
#2 /home/longfuse/forum.longfusegames.com/phpbb/extension/di/extension_base.php(63): phpbb\extension\di\extension_base->load_services(Object(Symfony\Component\DependencyInjection\Compiler\MergeExtensionConfigurationContainerBuilder))
#3 /home/longfuse/forum.longfusegames.com/vendor/symfony/dependency-injection/Compiler/MergeExtensionConfigurationPass.php(71): phpbb\extension\di\extension_base->load(Array, Object(Symfony\Component\DependencyInjection\Compiler\MergeExtensionConfigurationContainerBuilder))
#4 /home/longfuse/forum.longfusegames.com/vendor/symfony/http-kernel/DependencyInjection/MergeExtensionConfigurationPass.php(39): Symfony\Component\DependencyInjection\Compiler\MergeExtensionConfigurationPass->process(Object(Symfony\Component\DependencyInjection\ContainerBuilder))
#5 /home/longfuse/forum.longfusegames.com/vendor/symfony/dependency-injection/Compiler/Compiler.php(140): Symfony\Component\HttpKernel\DependencyInjection\MergeExtensionConfigurationPass->process(Object(Symfony\Component\DependencyInjection\ContainerBuilder))
#6 /home/longfuse/forum.longfusegames.com/vendor/symfony/dependency-injection/ContainerBuilder.php(789): Symfony\Component\DependencyInjection\Compiler\Compiler->compile(Object(Symfony\Component\DependencyInjection\ContainerBuilder))
#7 /home/longfuse/forum.longfusegames.com/phpbb/di/container_builder.php(203): Symfony\Component\DependencyInjection\ContainerBuilder->compile()
#8 /home/longfuse/forum.longfusegames.com/common.php(115): phpbb\di\container_builder->get_container()
#9 /home/longfuse/forum.longfusegames.com/adm/index.php(23): require('/home/longfuse/...')
#10 {main}

**Comment by Galixte** [comment]
Take a look to this PR: https://github.com/BoardTools/upload/pull/57/files.

**Comment by Neustradamus** [comment]
Can you confirm or not that it works perfectly with 3.3.x branch?
- https://github.com/BoardTools/upload/issues/63

Current is 3.3.14.
